language: node_js
node_js:
  - "9"

cache: yarn

jobs:
  include:
    - stage: GitHub Release
      script:
        - npm test
        - ng build --prod
      deploy:
        provider: releases
        skip_cleanup: true
        on:
          tags: true