language: node_js
node_js:
  - "9"

sudo: required

addons:
  mariadb: "10.3"
  chrome: stable

before_install:
  - sh ./server/setup_db_travis.sh 
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

jobs:
  include:
    - stage: GitHub Release
      script:
        - yarn test
        #- ng build --prod
      deploy:
        provider: releases
        skip_cleanup: true
        on:
          tags: true
