language: node_js
node_js:
  - "9"

addons:
  mariadb: "10.3"

before_install:
  - mysql -e "CREATE DATABASE usr_p100480_1;"
  - mysql usr_p100480_1 < ./server/usr_p100480_1.sql

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: GitHub Release
      script:
        - npm test
        - ng build --prod
      deploy:
        provider: releases
        skip_cleanup: true
        on:
          tags: true
